insert into csosn (codigo, descricao)
values ('101','Tributada pelo Simples Nacional com permissão de crédito');
insert into csosn (codigo, descricao)
values ('102','Tributada pelo Simples Nacional sem permissão de crédito');
insert into csosn (codigo, descricao)
values ('103','Isenção do ICMS no Simples Nacional para faixa de receita bruta');
insert into csosn (codigo, descricao)
values ('201','Tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS por sub. tributária');
insert into csosn (codigo, descricao)
values ('202','Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por sub. tributária');
insert into csosn (codigo, descricao)
values ('203','Isenção do ICMS no Simples Nacional p/ faixa de rec. bruta e com cob. do ICMS por sub. tributária');
insert into csosn (codigo, descricao)
values ('300','Imune');
insert into csosn (codigo, descricao)
values ('400','Não tributada pelo Simples Nacional');
insert into csosn (codigo, descricao)
values ('500','ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação');
insert into csosn (codigo, descricao)
values ('900','Outro');

commit;

