insert into cst(codigo,descricao) values('000','Tributada integralmente');
insert into cst(codigo,descricao) values('010','Tributada e com cobrança do ICMS por substituição tributária');
insert into cst(codigo,descricao) values('020','Com redução de base de cálculo');
insert into cst(codigo,descricao) values('030','Isenta ou não tributada e com cobrança do ICMS por substituição tributária');
insert into cst(codigo,descricao) values('040','Isenta');
insert into cst(codigo,descricao) values('041','Não tributada');
insert into cst(codigo,descricao) values('050','Suspensão');
insert into cst(codigo,descricao) values('051','Diferimento');
insert into cst(codigo,descricao) values('060','ICMS cobrado anteriormente por substituição tributária');
insert into cst(codigo,descricao) values('070','Com redução de base de cálculo e cobrança do ICMS por substituição tributária');
insert into cst(codigo,descricao) values('090','Outras');

commit work;
